### ISSUE TITLE
Error when CreateCommittedResource loading Cube map

### ISSUE THREAD

**Issue by fdsamxn** [mateeeeeee/Adria-DX12#2]
Hi when I run the project I found this error : 
`
D3D12 ERROR: ID3D12Device::CreateCommittedResource: D3D12_RESOURCE_DESC::Width, D3D12_RESOURCE_DESC::Height, and/ or D3D12_RESOURCE_DESC::DepthOrArraySize are too large for the D3D12_RESOURCE_DESC::Dimension and FeatureLevel. Width = 3435973836 and must be <= 16384, Height = 3435973836 and must be <= 16384, DepthOrArraySize = 1 and must be <= 2048, Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D, and FeatureLevel = D3D_FEATURE_LEVEL_12_1. [ STATE_CREATION ERROR #597: CREATERESOURCE_INVALIDDIMENSIONS]
`
`
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR STATE_CREATION #597: CREATERESOURCE_INVALIDDIMENSIONS ]
`

Apparently "equirect_hdr_image" Image has wrong dimension(3435973836 ,3435973836).
How can I solver this error?
Thx.

**Comment by mateeeeeee** [comment]
I am guessing it's because you don't have textures. Try downloading them from here: [here](https://github.com/mateeeeeee/Adria-DX11/releases/tag/1.0). Don't forget to move Textures folder inside Resources folder.

**Comment by fdsamxn** [comment]
> Some of the textures are needed for successful build. Try downloading them from [here](https://github.com/mateeeeeee/Adria-DX11/releases/tag/1.0). Don't forget to move Textures folder inside Resources folder.

Thx for the help, your are right, I missing the Texture resource, I didn`t check it before.
