### ISSUE TITLE
Missing resource textures

### ISSUE THREAD

**Issue by NPCompress** [mateeeeeee/Adria-DX12#3]
Application source is missing references to "Resources/Textures/..." folder

**Comment by mateeeeeee** [comment]
You can find textures in Release [here](https://github.com/mateeeeeee/Adria-DX11/releases/tag/1.0). Don't forget to move Textures folder inside Resources folder. Let me know if that worked for you.

**Comment by NPCompress** [comment]
Works perfectly. Thanks
