### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by MicrocosmeStudio** [mateeeeeee/Adria-DX12#5]
Hi,
Thanks for sharing this.
The project look nice and the code look net.

Unfortunately, i am not able to run successfully this project.
Can you add a short and sweet "how to" compile and run ?

About the textures:
I have add the entire Textures directory in the Resources directory.
Do it is the right ?

The solution compile fine (with some warnings but no errors) in debug and in release.
But the programme fail on start up.

The error in debug:
D3D12 ERROR: ID3D12CommandList::BuildRaytracingAccelerationStructure: D3D12_RAYTRACING_GEOMETRY_DESC.Triangles.IndexCount must be 0 when IndexBuffer is null (geometry [0]). [ RESOURCE_MANIPULATION ERROR #1158: BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INVALID]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR RESOURCE_MANIPULATION #1158: BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INVALID ]
Exception levée à 0x00007FFFFEF04FD9 (KernelBase.dll) dans Adria.exe : 0x0000087A (paramètres : 0x0000000000000001, 0x000000E62774A470, 0x000000E62774C240).
Exception non gérée à 0x00007FFFFEF04FD9 (KernelBase.dll) dans Adria.exe : 0x0000087A (paramètres : 0x0000000000000001, 0x000000E62774A470, 0x000000E62774C240).

The error in release:
Exception levée à 0x00007FFFFEF04FD9 dans Adria.exe : exception Microsoft C++ : _com_error à l'emplacement de mémoire 0x000000CC400FECC8.
Adria.exe a déclenché un point d'arrêt.

**Comment by mateeeeeee** [comment]
I did some changes in the last few days that might have broken the ray-tracing code, I will test it on RTX card soon, but in the meantime, can you try to download/clone an older version like this [one](https://github.com/mateeeeeee/Adria-DX12/tree/88acaf7f12903429cb11105f6c742607344be2f0) and let me know if you still get the same errors?
Thanks

**Comment by mateeeeeee** [comment]
Ok, there were some lines commented while I was refactoring, I've changed that and added commit so it should be working now (I haven't tested it on RTX card yet so if there are some other errors try what I've said in the previous comment).  Regarding your question "Can you add a short and sweet "how to" compile and run ?", you already did what is supposed to be done, this is a code bug, not a build problem. Let me know if it works for you.

**Comment by MicrocosmeStudio** [comment]
I get this assertion now:
With both the newest one and the with the older one.

Assertion failed!

Program: E:\dev\git\adria12\Adria-DX12\x64\Debug\Adria.exe
File: E:\dev\git\adria12\Adria-DX12\Adria...\D3D12Me...loc.cpp
Line: 4389

Expression: resAllocInfo.SizeInBytes > 0

**Comment by mateeeeeee** [comment]
Ok, I could reproduce the issue on RTX card, I've commited the fix and now hopefully it will work for you too. Let me know if it needs to be reopen.

**Comment by MicrocosmeStudio** [comment]
Hi,
The editor open up now.
Thanks :)
