### ISSUE TITLE
abort() has been called()

### ISSUE THREAD

**Issue by Celtics233** [mateeeeeee/Adria-DX12#7]
I haven’t identified any issues during debugging in Visual Studio, but I’m unable to successfully launch Adria.exe. I’ve tried various methods, yet the bug remains unresolved. Could you provide some advice? 😊

![image](https://github.com/mateeeeeee/Adria-DX12/assets/39730920/c374f239-aa0d-4205-a647-8e4ad7b6671a)

**Comment by mateeeeeee** [comment]
I suspect you ran a version where I accidentally left a gpu hang when testing nsight aftermath, I am closing this now. If you can reproduce it, please provide more details.
